language: node_js
node_js:
- 'lts/*'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npx yarn install
script:
  - npx yarn typedoc
deploy:
  provider: pages
  local-dir: ./docs
  target-branch: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
